import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/MainNav";
import Header from "@/components/Header";
import Footer from "@/components/Footer"
import AOSInit from "@/components/AOSInit"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aces Tennis Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="hidden 2xl:block">
          <MainNav />
        </div>
        <div className="w-full max-w-[1130px] px-[15px] mx-auto">
          <Header />
        </div>
        <AOSInit />
        {children}
        <div className="w-full ">
          <Footer />
        </div>
      </body>
    </html>
  );
}
